INFO     root:log_utils.py:24 错误信息，nameerror
ERROR    root:test_wangxue.py:11 error
DEBUG    root:log_utils.py:21 debug